# Generated by Django 4.1.5 on 2023-09-04 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('price', models.IntegerField(verbose_name='price')),
                ('title_description', models.CharField(max_length=255, verbose_name='title description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'apartment',
                'verbose_name_plural': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_messenger', models.CharField(blank=True, max_length=255, null=True, verbose_name='name_messenger')),
                ('link_messenger', models.CharField(blank=True, max_length=255, null=True, verbose_name='link_messanger')),
            ],
            options={
                'verbose_name': 'messenger',
                'verbose_name_plural': 'messengers',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='apartment_images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='PhotoApartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo',
            field=models.ManyToManyField(through='apartments.PhotoApartment', to='apartments.photo'),
        ),
    ]
